# Generated by Django 4.1.5 on 2023-01-30 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0002_alter_product_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("locality", models.CharField(max_length=70)),
                ("city", models.CharField(max_length=80)),
                ("mobile", models.IntegerField(default=0)),
                ("zipcode", models.IntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("AC", "Accra"),
                            ("ML", "Milk"),
                            ("LS", "Lassi"),
                            ("MS", "Milkshake"),
                            ("PN", "Paneer"),
                            ("GH", "Ghee"),
                            ("CZ", "Cheese"),
                            ("IC", "Ice-Creams"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
