# Generated by Django 4.1.4 on 2023-02-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_customer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="User",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="customer",
            name="mobile",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="customer",
            name="state",
            field=models.CharField(
                choices=[
                    ("AC", "Accra"),
                    ("LG", "Lagos"),
                    ("AB", "Abuja"),
                    ("PR", "Pretoria"),
                    ("NA", "Nairobi"),
                    ("RA", "Rabat"),
                    ("AL", "Alger"),
                    ("CA", "Caire"),
                ],
                max_length=2,
            ),
        ),
    ]
